### ISSUE TITLE
Bug: Feil i fil G16FinaleStart.csv

### ISSUE THREAD

**Issue by heming-langrenn** [heming-langrenn/sprint-excel#14]
Ser ut som om dette er komplette resultatlister - blitt feil behandlet? Sjekk i excel-fil @heming-langrenn .

**Comment by heming-langrenn** [comment]
@stigbd - datapusher kræsjet når denne filen ble prosessert. Er det mulig å endre datapusher slik at den heller ignorerer filen?

**Comment by stigbd** [comment]
Takker, skal få laga ein test som gjenskaper problemet. Skiller denne seg frå andre finale-filer?

**Comment by heming-langrenn** [comment]
Det var en bug i fila, har fikset det nå. Oppdatert .xls og testfiler.
