### ISSUE TITLE
Bug: Startnummer importeres på ulikt format

### ISSUE THREAD

**Issue by heming-langrenn** [heming-langrenn/sprint-excel#16]
Fra filen "Deltakere.txt" importeres startnumer til database som et desimaltall - alle nummer får .0 som avslutning. Dette gjøres ikke  i startlister og dermed blir det problematisk å koble data. @stigbd , forslag til hvordan vi løser dette?

**Comment by stigbd** [comment]
Har endra slik at startnummer frå Deltaktere.csv blir tolka som string. Dette er likt som for startlister. Eg tenker det dermed skal vere mulig å koble data. Viss det stadig ikkje fungerer, kan vi evt vurdere å behandle alle startnummer i alle filer som integer.

**Comment by heming-langrenn** [comment]
Testet OK. Har også lagt inn en sjekk som fjerner .0 hvis dette eksisterer i startnummer.
